### ISSUE TITLE
Regenerated QR code Is Invalid

### ISSUE THREAD

**Issue by jweaver0312** [hwdsl2/wireguard-install#37]
**Describe the issue**
Wireguard app says regenerated QR code is invalid

**To Reproduce**

1. Install using default settings (auto)
2. ran `qrencode -t UTF8 < /root/client.conf`

**Server (please complete the following information)**
- OS: AlmaLinux 9

**Client (please complete the following information)**
- Device: iPhone 14 Pro Max
- OS: iOS 17.5.1

**Comment by hwdsl2** [comment]
@jweaver0312 Hello! Please run `sudo bash wireguard.sh` and select option "4) Show QR code for a client" to regenerate the QR code for a client. If that doesn't work, try adding a new client instead. For the issue you encountered, it may be because `/root/client.conf` does not exist or is corrupted. Note that when using `sudo`, the script normally creates client config files under the user's home directory, instead of `/root`.
